update: project gradle dependencies and support android 30
- fix gradle implementations
- move ServiceJobTask as another java file
- add deprecated unused classes
- TODO: fix ERROR Logs below

ERROR: 04/13 13:45:19: Launching 'app' on Xiaomi Redmi Note 9 Pro.
Installation did not succeed.
The application could not be installed: INSTALL_FAILED_NO_MATCHING_ABIS

List of apks:
[0] '/Users/ffuf/myproject/techelm-master/app/build/outputs/apk/debug/app-debug.apk'
Installation failed due to: 'null'
Retry